---
- name: configure red hat custom rpm key
  rpm_key:
    key: "{{ ceph_custom_key }}"
    state: present
  register: result
  until: result is succeeded
  when: ceph_custom_key is defined


#- name: configure red hat custom repository
#  get_url:
  #  url: "{{ ceph_custom_repo }}"
  #  dest: /etc/yum.repos.d
  #  owner: root
  #  group: root


- name: configure red hat custom repository
  yum_repository:
    name: ceph_custom
    description: Ceph Custom Repo
    gpgcheck: yes
    state: present
    gpgkey: "{{ ceph_custom_key }}"
    baseurl: "{{ ceph_custom_repo }}"
    file: ceph_custom
    priority: 2
  register: result
  until: result is succeeded
